name: Build LaTex Thesis

on:
  push:
    paths:
      - 'thesis/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: { image: 'aergus/latex' }
    defaults:
      run:
        working-directory: thesis

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the thesis
        run: latexmk -pdf thesis

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: Bachelor Thesis
          path: thesis/thesis.pdf
