name: Build LaTex Thesis

on:
  push:
    paths:
      - 'thesis/**'
      - '.github/workflows/thesis.yml'
  workflow_dispatch:

jobs:
  build-thesis:
    runs-on: ubuntu-latest
    container: { image: 'aergus/latex' }
    defaults:
      run:
        working-directory: thesis

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Thesis
        run: make

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: Thesis
          path: thesis/thesis.pdf
